# encoding: UTF-8
# Generated by tools/support/quiz_pack_writer.rb; do not edit the checksum by hand.
# Source: Base pack: https://github.com/budyn1211/elten-game-room/blob/efa6e640a57901e7b01e5ac2158e84f1c3375435/content/quiz_pl_wikidata.rb; sport corrections: content/QUIZ_PL_SPORT_SOURCES.txt
# Sport corrections: https://github.com/papierek1997/elten-game-room/commit/2e043a8e0cf5b68df0799a5ffc4a1bb791b24a25
require_relative "../lib/game_content"
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "quiz.wikidata.pl",
  set_id: "quiz.wikidata",
  kind: :quiz,
  language_id: "pl-PL",
  version: 6,
  title: "Wiedza ogólna: chemia, geografia, sport, wiara, historia",
  game_ids: ["quiz"],
  license: "CC0-1.0",
  author: "ELTEN Game Room",
  entry_count: 11083,
  checksum: "be5969211d041e624e251630efdcf4260e191b683ce03e1ee5261cd8b53fcc7e",
  loader: lambda {
    require_relative "quiz_pl_wikidata_data"
    GameRoomContent::Packa0830f585cc4689a1e2a6335.load
  }
))
