# encoding: UTF-8
require_relative "../lib/game_room_localization"
# Generated by tools/support/quiz_pack_writer.rb; do not edit the checksum by hand.
# Source: https://github.com/budyn1211/elten-game-room/blob/efa6e640a57901e7b01e5ac2158e84f1c3375435/content/quiz_general_en.rb
require_relative "../lib/game_content"
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "quiz.general.en",
  set_id: "quiz.general",
  kind: :quiz,
  language_id: "en",
  version: 4,
  title: GameRoomLocalization.translate("General knowledge"),
  game_ids: ["quiz"],
  license: "CC-BY-SA-4.0",
  author: "OpenTriviaQA contributors",
  entry_count: 13903,
  checksum: "4f1cf5d680f8387506bf0b65e456404aa4a102591f1617540dc61c1ec1b09634",
  loader: lambda {
    require_relative "quiz_general_en_data"
    GameRoomContent::Pack0e7a79bfbaaded2145287ed3.load
  }
))
