# encoding: UTF-8
# Generated by tools/support/quiz_pack_writer.rb; do not edit the checksum by hand.
# Source: content/QUIZ_PL_GENERAL_SOURCES.txt
require_relative "../lib/game_content"
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "quiz.wikidata.pl",
  set_id: "quiz.wikidata",
  kind: :quiz,
  language_id: "pl-PL",
  version: 8,
  title: "Wiedza ogólna",
  game_ids: ["quiz"],
  license: "Mixed: CC-BY-SA-4.0 (PolQA/MAUPQA); Milionerzy by permission. See QUIZ_PL_GENERAL_SOURCES.txt",
  author: "PolQA/MAUPQA (IPI PAN), Polsat; adaptation for Power Games",
  entry_count: 14887,
  checksum: "8a5d0db5bfea754a21940892cab235752582e7f1bb66bc1886df38a743ea1406",
  loader: lambda {
    require_relative "quiz_pl_wikidata_data"
    GameRoomContent::Packa0830f585cc4689a1e2a6335.load
  }
))
