require 'json'

module GameRoomTest
  module TranslationReference
    # Independent expected wording, never regenerated by the translation CLI.
    DATA = JSON.parse(File.read(File.expand_path('../fixtures/polish_messages.json', __dir__), encoding: 'UTF-8'))
    DATA.each_value { |messages| messages.each_value(&:freeze); messages.freeze }
    DATA.freeze

    def self.fetch(group)
      DATA.fetch(group.to_s)
    end
  end
end
