# encoding: UTF-8
require "json"
require "fileutils"
require_relative "../../lib/game_content"

# Ruby resources are used deliberately: ELTEN's signed program loader supports
# require_relative, whereas arbitrary File reads from a virtual package do not.
module QuizPackWriter
  module_function

  def literal(value)
    value.inspect
  end

  def write(path, metadata, questions, source: nil, translated: false)
    metadata = metadata.reject { |key, _| [:data, :loader, :checksum, :entry_count].include?(key) }
    data = { questions: questions }
    data[:source] = source if source
    pack = GameRoomContent::Pack.new(**metadata, data: data)
    module_name = "Pack#{Digest::SHA256.hexdigest(pack.id)[0, 24]}"
    basename = File.basename(path, ".rb") + "_data"
    data_path = File.join(File.dirname(path), basename + ".rb")
    json = JSON.generate(pack.data)
    # Single quoted heredoc prevents question text from becoming Ruby code.
    delimiter = "QUIZ_DATA_#{pack.checksum}"
    raise "unsafe data delimiter" if json.lines.any? { |line| line.strip == delimiter }
    body = "# encoding: UTF-8\nrequire 'json'\nmodule GameRoomContent\n  module #{module_name}\n    def self.load\n      JSON.parse(<<'#{delimiter}')\n"
    body << JSON.pretty_generate(pack.data) << "\n#{delimiter}\n    end\n  end\nend\n"
    File.write(data_path, body, encoding: "UTF-8")
    lines = ["# encoding: UTF-8"]
    lines << 'require_relative "../lib/game_room_localization"' if translated
    lines << "# Generated by tools/support/quiz_pack_writer.rb; do not edit the checksum by hand."
    lines << "# Source: #{source.to_s.gsub(/[[:cntrl:]]+/, ' ')}" if source
    lines << 'require_relative "../lib/game_content"'
    lines << 'GameRoomContent.registry.register_pack(GameRoomContent::Pack.new('
    metadata.each do |key, value|
      expression = key == :title && translated ? "GameRoomLocalization.translate(#{literal(value)})" : literal(value)
      lines << "  #{key}: #{expression},"
    end
    lines << "  entry_count: #{questions.length},"
    lines << "  checksum: #{literal(pack.checksum)},"
    lines << "  loader: lambda {"
    lines << "    require_relative #{literal(basename)}"
    lines << "    GameRoomContent::#{module_name}.load"
    lines << "  }"
    lines << "))"
    File.write(path, lines.join("\n") + "\n", encoding: "UTF-8")
    pack
  end
end
