# Reproducible offline transformation. Download the named, licensed sources
# separately; this tool never substitutes an unversioned network response.
require "json"
require "zlib"
require "base64"
require "digest"
require_relative "../lib/game_content"

source_dir = File.expand_path(ARGV.fetch(0))
destination = File.expand_path("../content", __dir__)
sources = [
  { language: "en", input: "wordlist-20210729.txt", source: "https://github.com/wordnik/wordlist/blob/46e6215d0f90356afe9c8ba4be347e7e98cb425c/wordlist-20210729.txt",
    author: "Wordnik", license: "MIT", title: "English — Wordnik (2021-07-29)", alphabet: /\A[a-z]{2,15}\z/,
    sha: "bfd1b4eb4ade1ba81e84c7e24248b9a1aecec9d9baa427453b367a83e30e0451" },
  { language: "pl-PL", input: "sjp/slowa.txt", source: "https://sjp.pl/sl/growy/sjp-20260901.zip",
    author: "SJP.PL contributors", license: "CC-BY-4.0", title: "Polski — SJP (2026-09-01)", alphabet: /\A[aąbcćdeęfghijklłmnńoóprsśtuwyzźż]{2,15}\z/ }
]
report = []
sources.each do |source|
  bytes = File.binread(File.join(source_dir, source[:input]))
  sha = Digest::SHA256.hexdigest(bytes)
  raise "Source checksum mismatch" if source[:sha] && sha != source[:sha]
  text = bytes.force_encoding("UTF-8")
  raise "Source is not UTF-8" unless text.valid_encoding?
  total = 0
  words = []
  text.each_line do |line|
    total += 1
    word = UnicodeNormalize.normalize(line.strip.delete_prefix('"').delete_suffix('"'), :nfc).downcase
    words << word if source[:alphabet].match?(word)
  end
  words.sort!.uniq!
  chunks = words.each_slice(2048).to_a
  data = { "keys" => chunks.map(&:first), "blocks" => chunks.map { |chunk| Base64.strict_encode64(Zlib::Deflate.deflate(chunk.join("\n"), 9)) },
    "source" => source[:source], "source_sha256" => sha, "count" => words.length }
  id = "scrabble.words.#{source[:language].downcase}.v1"
  metadata = { id: id, set_id: "scrabble.words.#{source[:language].downcase}", kind: "word_dictionary", language_id: source[:language], version: 1,
    title: source[:title], game_ids: ["scrabble"], author: source[:author], license: source[:license], entry_count: words.length }
  pack = GameRoomContent::Pack.new(**metadata, data: data)
  name = "scrabble_words_#{source[:language] == 'en' ? 'en' : 'pl'}"
  mod = source[:language] == "en" ? "ScrabbleWordsEN" : "ScrabbleWordsPL"
  # Ruby resources work both in a checkout and ELTEN's binary application loader.
  body = "# encoding: UTF-8\n# Generated by tools/build-scrabble-dictionaries.rb.\nrequire 'json'\nmodule GameRoomContent::#{mod}\n  def self.load\n    JSON.parse(<<'WORDS_#{pack.checksum}')\n#{JSON.generate(pack.data)}\nWORDS_#{pack.checksum}\n  end\nend\n"
  File.write(File.join(destination, "#{name}_data.rb"), body, encoding: "UTF-8")
  entry = "# encoding: UTF-8\n# Source and license: WORD_DICTIONARIES_NOTICE.md\nrequire_relative '../lib/game_content'\nmodule GameRoomContent::#{mod}; end\nGameRoomContent.registry.register_pack(GameRoomContent::Pack.new(\n"
  metadata.each { |key, value| entry << "  #{key}: #{value.inspect},\n" }
  entry << "  checksum: #{pack.checksum.inspect},\n  loader: lambda { require_relative '#{name}_data'; GameRoomContent::#{mod}.load }\n))\n"
  File.write(File.join(destination, "#{name}.rb"), entry, encoding: "UTF-8")
  report << { language: source[:language], input_lines: total, retained: words.length, blocks: chunks.length, source_sha256: sha, pack_checksum: pack.checksum }
end
puts JSON.pretty_generate(report)
