require 'optparse'
require 'digest'

module GameRoomNounGenerator
  ROOT = File.expand_path('..', __dir__)
  module_function

  def render(text)
    raise 'Noun source must be valid UTF-8 with LF endings' unless text.encoding == Encoding::UTF_8 && text.valid_encoding? && !text.include?("\r")
    words = text.lines.map(&:chomp)
    raise 'Noun source is empty or contains blank entries' if words.empty? || words.any? { |word| word.strip.empty? }
    raise 'Unsafe noun heredoc delimiter' if words.any? { |word| word.match?(/\A[ \t]*KROWA_NOUNS\z/) }
    "# encoding: UTF-8\n# This file is generated by tools/generate-krowa-nouns.rb.\n\n" +
      "module GameRoomKrowa\n  module NounData\n    WORDS = <<~'KROWA_NOUNS'\n" +
      words.map { |word| "      #{word}\n" }.join +
      "    KROWA_NOUNS\n    WORDS.freeze\n  end\nend\n"
  end

  def run(root: ROOT, check: false)
    input = File.join(root, 'tools/data/krowa_nouns.txt')
    output = File.join(root, 'games/krowa_support/noun_data.rb')
    text = File.read(input, encoding: 'UTF-8')
    generated = render(text)
    same = File.file?(output) && File.binread(output) == generated.b
    raise 'Stale noun data; run ruby tools/generate-krowa-nouns.rb' if check && !same
    File.binwrite(output, generated) unless check || same
    {entries: text.lines.length, source_sha256: Digest::SHA256.hexdigest(text), changed: !same}
  end
end

if $PROGRAM_NAME == __FILE__
  options = {}
  OptionParser.new do |parser|
    parser.on('--check') { options[:check] = true }
    parser.on('--root DIRECTORY') { |value| options[:root] = File.expand_path(value) }
  end.parse!
  abort 'Unexpected arguments' unless ARGV.empty?
  puts GameRoomNounGenerator.run(**options).inspect
end
